package cn.cadal.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import common.utils.HashCodeUtil;
	

/**
* MyPage generated by hbm2java 
**/
@Entity
@Table (name="CUserPage")
public class MyPage  implements java.io.Serializable {
	
	
	// Fields
	private int id;
	
	private Cuser user;
	
	private Cbook book;

    private Integer pageNo;

	// Constructors

	/** default constructor */
	public MyPage() {
	}	

	/** full constructor */
	public MyPage(Cuser user, Cbook book, Integer pageNo) {
		this.user = user;
		this.book = book;
		this.pageNo = pageNo;
		
	}

	@Column (name="Page")
	public Integer getPageNo() {
		return this.pageNo;
	}
	
	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}
	
	@ManyToOne()
	@JoinColumn(name="BookNo")
	public Cbook getBook() {
		return book;
	}

	public void setBook(Cbook book) {
		this.book = book;
	}


	@ManyToOne()
	@JoinColumn(name="UserID")
	public Cuser getUser() {
		return user;
	}

	public void setUser(Cuser user) {
		this.user = user;
	}
	
	@Id
	@GeneratedValue (strategy=GenerationType.AUTO)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public boolean equals (Object right){
		MyPage rightUB = (MyPage) right;
		boolean ret = false;
		ret = (this.getUser().getUserId()== rightUB.getUser().getUserId())
			&&(this.getBook().getBookNo() == rightUB.getBook().getBookNo());
		return ret;
	}

	public int hashCode () {
		int result = HashCodeUtil.SEED;
		result = HashCodeUtil.hash(result, getUser().getUserId());
		result = HashCodeUtil.hash(result, getBook().getBookNo());
		return result;
	}
}















