package cn.cadal.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import common.utils.HashCodeUtil;
	

/**
* MyRanking generated by hbm2java 
**/
@Entity
@Table (name="CUserRating")
public class MyRanking  implements java.io.Serializable {

	
	
	// Fields
	private int id;
	
	private Cuser user;
	
	private Cbook book;

    private Integer rate;

	// Constructors

	/** default constructor */
	public MyRanking() {
	}
	
	public MyRanking (Cuser user, Cbook book ) {
		this.user = user;
		this.book = book;
	}

	/** full constructor */
	public MyRanking(Cuser user, Cbook book, Integer rate) {
		this.user = user;
		this.book = book;
		this.rate = rate;
		
	}
	
	


	@Column (name="Rate")
	public Integer getRate() {
		return this.rate;
	}
	
	public void setRate(Integer rate) {
		this.rate = rate;
	}
	
	@ManyToOne()
	@JoinColumn(name="BookNo")
	public Cbook getBook() {
		return book;
	}

	public void setBook(Cbook book) {
		this.book = book;
	}


	@ManyToOne()
	@JoinColumn(name="UserID")
	public Cuser getUser() {
		return user;
	}

	public void setUser(Cuser user) {
		this.user = user;
	}
	
	@Id
	@GeneratedValue (strategy=GenerationType.AUTO)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public boolean equals (Object right){
		MyRanking rightUB = (MyRanking) right;
		boolean ret = false;
		ret = (this.getUser().getUserId()== rightUB.getUser().getUserId())
			&&(this.getBook().getBookNo() == rightUB.getBook().getBookNo());
		return ret;
	}

	public int hashCode () {
		int result = HashCodeUtil.SEED;
		result = HashCodeUtil.hash(result, getUser().getUserId());
		result = HashCodeUtil.hash(result, getBook().getBookNo());
		return result;
	}
}















