package cn.cadal.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import common.utils.HashCodeUtil;


/**
 * UserBinders generated by hbm2java
 */
@Entity
@Table (name="CUserBinders")
public class UserBinder implements java.io.Serializable {

	// Fields
	private int id;
	
	private Cuser user;
	
	private Cbinder bindBinder;

	private int topNum;

	// Constructors

	/** default constructor */
	public UserBinder() {
	}
	
	public UserBinder (Cuser user, Cbinder binder ) {
		this.user = user;
		this.bindBinder = binder;
	}

	/** full constructor */
	public UserBinder(Cuser user, Cbinder binder, int topNum) {
		this.user = user;
		this.bindBinder = binder;
		this.topNum = topNum;
	}

	@Column (name="TopNum")
	public int getTopNum() {
		return this.topNum;
	}

	public void setTopNum(int topNum) {
		this.topNum = topNum;
	}
	
	@ManyToOne()
	@JoinColumn(name="BinderID")
	public Cbinder getBindBinder() {
		return bindBinder;
	}

	public void setBindBinder(Cbinder bindBinder) {
		this.bindBinder = bindBinder;
	}

	@ManyToOne()
	@JoinColumn(name="UserID")
	public Cuser getUser() {
		return user;
	}

	public void setUser(Cuser user) {
		this.user = user;
	}
	
	@Id
	@GeneratedValue (strategy=GenerationType.AUTO)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public boolean equals (Object right){
		UserBinder rightUB = (UserBinder) right;
		boolean ret = false;
		ret = (this.getUser().getUserId()== rightUB.getUser().getUserId())
			&&(this.getBindBinder().getBinderId() == rightUB.getBindBinder().getBinderId());
		return ret;
	}

	public int hashCode () {
		int result = HashCodeUtil.SEED;
		result = HashCodeUtil.hash(result, getUser().getUserId());
		result = HashCodeUtil.hash(result, getBindBinder().getBinderId());
		return result;
	}
}
