/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.test;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserRequest implements org.apache.thrift.TBase<UserRequest, UserRequest._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserRequest");

  private static final org.apache.thrift.protocol.TField IDENTITYCARD_FIELD_DESC = new org.apache.thrift.protocol.TField("identitycard", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserRequestTupleSchemeFactory());
  }

  public String identitycard; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IDENTITYCARD((short)1, "identitycard");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IDENTITYCARD
          return IDENTITYCARD;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IDENTITYCARD, new org.apache.thrift.meta_data.FieldMetaData("identitycard", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserRequest.class, metaDataMap);
  }

  public UserRequest() {
  }

  public UserRequest(
    String identitycard)
  {
    this();
    this.identitycard = identitycard;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserRequest(UserRequest other) {
    if (other.isSetIdentitycard()) {
      this.identitycard = other.identitycard;
    }
  }

  public UserRequest deepCopy() {
    return new UserRequest(this);
  }

  public void clear() {
    this.identitycard = null;
  }

  public String getIdentitycard() {
    return this.identitycard;
  }

  public UserRequest setIdentitycard(String identitycard) {
    this.identitycard = identitycard;
    return this;
  }

  public void unsetIdentitycard() {
    this.identitycard = null;
  }

  /** Returns true if field identitycard is set (has been assigned a value) and false otherwise */
  public boolean isSetIdentitycard() {
    return this.identitycard != null;
  }

  public void setIdentitycardIsSet(boolean value) {
    if (!value) {
      this.identitycard = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IDENTITYCARD:
      if (value == null) {
        unsetIdentitycard();
      } else {
        setIdentitycard((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IDENTITYCARD:
      return getIdentitycard();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IDENTITYCARD:
      return isSetIdentitycard();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserRequest)
      return this.equals((UserRequest)that);
    return false;
  }

  public boolean equals(UserRequest that) {
    if (that == null)
      return false;

    boolean this_present_identitycard = true && this.isSetIdentitycard();
    boolean that_present_identitycard = true && that.isSetIdentitycard();
    if (this_present_identitycard || that_present_identitycard) {
      if (!(this_present_identitycard && that_present_identitycard))
        return false;
      if (!this.identitycard.equals(that.identitycard))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(UserRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    UserRequest typedOther = (UserRequest)other;

    lastComparison = Boolean.valueOf(isSetIdentitycard()).compareTo(typedOther.isSetIdentitycard());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdentitycard()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.identitycard, typedOther.identitycard);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserRequest(");
    boolean first = true;

    sb.append("identitycard:");
    if (this.identitycard == null) {
      sb.append("null");
    } else {
      sb.append(this.identitycard);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserRequestStandardSchemeFactory implements SchemeFactory {
    public UserRequestStandardScheme getScheme() {
      return new UserRequestStandardScheme();
    }
  }

  private static class UserRequestStandardScheme extends StandardScheme<UserRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IDENTITYCARD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.identitycard = iprot.readString();
              struct.setIdentitycardIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.identitycard != null) {
        oprot.writeFieldBegin(IDENTITYCARD_FIELD_DESC);
        oprot.writeString(struct.identitycard);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserRequestTupleSchemeFactory implements SchemeFactory {
    public UserRequestTupleScheme getScheme() {
      return new UserRequestTupleScheme();
    }
  }

  private static class UserRequestTupleScheme extends TupleScheme<UserRequest> {

    public void write(org.apache.thrift.protocol.TProtocol prot, UserRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIdentitycard()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals);
      if (struct.isSetIdentitycard()) {
        oprot.writeString(struct.identitycard);
      }
    }

    public void read(org.apache.thrift.protocol.TProtocol prot, UserRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.identitycard = iprot.readString();
        struct.setIdentitycardIsSet(true);
      }
    }
  }

}

